import Image from "next/image"
import { RecentItemType, RecentItemTypeEnum } from "@/schemas/utils"
import {
  AlertTriangle,
  AppWindow,
  Archive,
  ArrowDown,
  ArrowRight,
  ArrowUp,
  ArrowUpCircleIcon,
  ArrowUpDown,
  AtSignIcon,
  BadgeCheck,
  BarChart,
  Bell,
  BookIcon,
  BookImageIcon,
  BookOpenText,
  Brain,
  Calendar,
  CalendarSearchIcon,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsRightIcon,
  ChevronsUpDown,
  Circle,
  Clock,
  CoinsIcon,
  CopyIcon,
  CreditCard,
  DatabaseZapIcon,
  DollarSign,
  ExternalLink,
  EyeIcon,
  EyeOff,
  File,
  FileText,
  Filter,
  Folder,
  GithubIcon,
  GlobeIcon,
  Grid3X3Icon,
  HelpCircle,
  HomeIcon,
  HospitalIcon,
  Image as ImageIcon,
  Inbox,
  Info,
  KeyIcon,
  Laptop,
  LayoutDashboardIcon,
  LineChartIcon,
  ListIcon,
  Loader2,
  LockIcon,
  LogIn,
  LogOut,
  LogsIcon,
  LucideIcon,
  MailIcon,
  MapPin,
  Menu,
  Monitor,
  Moon,
  MoreVertical,
  MoreVerticalIcon,
  Move,
  PencilIcon,
  PhoneIcon,
  Pizza,
  Plus,
  PuzzleIcon,
  RefreshCw,
  RssIcon,
  SaveIcon,
  Search,
  Settings,
  Share,
  Shield,
  Sparkles,
  SquaresIntersectIcon,
  SquareTerminal,
  Stethoscope,
  StretchHorizontalIcon,
  SunMedium,
  TagIcon,
  ToggleRightIcon,
  Trash,
  Trash2,
  TrendingDown,
  TrendingUp,
  UserCircleIcon,
  UserCogIcon,
  UserPlus,
  Users,
  X,
  ZapIcon,
} from "lucide-react"

import { cn } from "@/lib/utils"

export type Icon = LucideIcon

function LogoIcon({ className }: { className?: string }) {
  return <span className={cn(className)}>🔐</span>
}

function LastPassIcon({ className }: { className?: string }) {
  return (
    <Image
      src="/logos/lastpass.svg"
      alt="LastPass"
      width={48}
      height={48}
      className={cn(className, "inline-block object-contain align-middle")}
    />
  )
}

function HashiCorpIcon({ className }: { className?: string }) {
  return (
    <Image
      src="/logos/hashicorp.svg"
      alt="HashiCorp"
      width={48}
      height={48}
      className={cn(className, "inline-block object-contain align-middle")}
    />
  )
}

export const Icons = {
  logo: LogoIcon,
  logoLucide: ChevronsRightIcon,
  close: X,
  up: ArrowUp,
  down: ArrowDown,
  right: ChevronRight,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  post: FileText,
  page: File,
  media: ImageIcon,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: AlertTriangle,
  user: UserCircleIcon,
  arrowRight: ArrowRight,
  help: HelpCircle,
  pizza: Pizza,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  search: Search,
  check: Check,
  orderbook: BookOpenText,
  chevronsUpDown: ChevronsUpDown,
  phone: PhoneIcon,
  mail: MailIcon,
  pencil: PencilIcon,
  student: PencilIcon,
  teacher: UserCogIcon,
  monitor: Monitor,
  databaseZap: DatabaseZapIcon,
  blog: BookImageIcon,
  graph: LineChartIcon,
  zap: ZapIcon,
  copy: CopyIcon,
  toggleRight: ToggleRightIcon,
  creditCard: CreditCard,
  calendar: Calendar,
  barChart: BarChart,
  clock: Clock,
  brain: Brain,
  menu: Menu,
  document: BookIcon,
  folder: Folder,
  more: MoreVerticalIcon,
  badgeCheck: BadgeCheck,
  bell: Bell,
  logOut: LogOut,
  sparkles: Sparkles,
  studio: SquareTerminal,
  register: UserPlus,
  appointment: CalendarSearchIcon,
  coins: CoinsIcon,
  location: MapPin,
  trendingUp: TrendingUp,
  trendingDown: TrendingDown,
  dollarSign: DollarSign,
  users: Users,
  inbox: Inbox,
  arrowUpDown: ArrowUpDown,
  circle: Circle,
  helpCircle: HelpCircle,
  shield: Shield,
  therapist: Stethoscope,
  staff: Users,
  pending: Loader2,
  approved: Check,
  rejected: X,
  contacted: MailIcon,
  demoScheduled: CalendarSearchIcon,
  demoCompleted: Check,
  contractSigned: FileText,
  onboarding: UserCogIcon,
  joined: UserPlus,
  save: SaveIcon,
  question: HelpCircle,
  clinic: HospitalIcon,
  edit: PencilIcon,
  userPlus: UserPlus,
  leave: LogOut,
  chevronDown: ChevronDown,
  dashboard: LayoutDashboardIcon,
  lifecycle: ListIcon,
  arrowUpCircle: ArrowUpCircleIcon,
  key: KeyIcon,
  home: HomeIcon,
  account: AtSignIcon,
  info: Info,
  refresh: RefreshCw,
  login: LogIn,
  lastPass: LastPassIcon,
  hashicorp: HashiCorpIcon,
  github: GithubIcon,
  logs: LogsIcon,
  grid: Grid3X3Icon,
  list: ListIcon,
  eye: EyeIcon,
  eyeOff: EyeOff,
  trash2: Trash2,
  view: StretchHorizontalIcon,
  filter: Filter,
  tag: TagIcon,
  globe: GlobeIcon,
  lock: LockIcon,
  puzzle: PuzzleIcon,
  share: Share,
  move: Move,
  apps: AppWindow,
  archive: Archive,
  iv: SquaresIntersectIcon,
  platform: RssIcon,
  link: ExternalLink,
}

export const getEntityIcon = (itemType: RecentItemType) => {
  switch (itemType) {
    case RecentItemTypeEnum.CREDENTIAL:
      return <AtSignIcon className="size-4" />
    case RecentItemTypeEnum.CARD:
      return <CreditCard className="size-4" />
    case RecentItemTypeEnum.SECRET:
      return <KeyIcon className="size-4" />
  }
}
