import { createContext } from "@/orpc/context"
import { appRouter } from "@/orpc/routers"
import { RPCHandler } from "@orpc/server/fetch"

const handler = new RPCHandler(appRouter)

/**
 * Handles incoming HTTP requests for the oRPC API route, delegating them to the RPC handler and returning the appropriate response.
 *
 * @param request - The incoming HTTP request to process
 * @returns The response generated by the RPC handler, or a 404 response if no response is produced
 */
async function handleRequest(request: Request) {
  const { response } = await handler.handle(request, {
    prefix: "/api/orpc",
    context: await createContext(),
  })

  return response ?? new Response("Not found", { status: 404 })
}

export const GET = handleRequest
export const POST = handleRequest
export const PUT = handleRequest
export const PATCH = handleRequest
export const DELETE = handleRequest
